"""empty message

Revision ID: 173a71dc7705
Revises: 338c38ef7079
Create Date: 2021-03-16 16:19:09.463749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173a71dc7705'
down_revision = '338c38ef7079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
