"""empty message

Revision ID: 1794c33b4b58
Revises: 173a71dc7705
Create Date: 2021-03-18 14:02:19.367427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1794c33b4b58'
down_revision = '173a71dc7705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_user', sa.Column('file', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'document_user', ['file'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_user', type_='unique')
    op.drop_column('document_user', 'file')
    # ### end Alembic commands ###
