"""empty message

Revision ID: 338c38ef7079
Revises: fa4ac157e451
Create Date: 2021-03-14 18:09:10.075302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338c38ef7079'
down_revision = 'fa4ac157e451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('status1', 'status2', 'status3', 'status4', 'status5', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('folder_user_document_folder_id_fkey', 'folder_user', type_='foreignkey')
    op.create_foreign_key(None, 'folder_user', 'document_folder', ['document_folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folder_user', type_='foreignkey')
    op.create_foreign_key('folder_user_document_folder_id_fkey', 'folder_user', 'promo', ['document_folder_id'], ['id'])
    op.drop_table('document_user')
    # ### end Alembic commands ###
