"""empty message

Revision ID: efc8da1e2518
Revises: 1ee04050d07e
Create Date: 2021-04-07 11:28:37.100916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc8da1e2518'
down_revision = '1ee04050d07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_user', sa.Column('folder_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('folder_user_document_folder_id_fkey', 'folder_user', type_='foreignkey')
    op.create_foreign_key(None, 'folder_user', 'folder_type', ['folder_type_id'], ['id'])
    op.drop_column('folder_user', 'document_folder_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_user', sa.Column('document_folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'folder_user', type_='foreignkey')
    op.create_foreign_key('folder_user_document_folder_id_fkey', 'folder_user', 'document_folder', ['document_folder_id'], ['id'])
    op.drop_column('folder_user', 'folder_type_id')
    # ### end Alembic commands ###
